# Generated by Django 4.0.3 on 2022-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_category_options_alter_photo_options_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='destination',
            field=models.CharField(default='Woolwich Community Services', max_length=30),
            preserve_default=False,
        ),
    ]
